-- Este arquivo será carregado automaticamente pelo SpringBoot quando a aplicação for iniciada. --
-- O banco já deve estar configurado --

DROP TABLE IF EXISTS funcionarios;
DROP TABLE IF EXISTS pagamentos;
DROP TABLE IF EXISTS detalhes;
 
CREATE TABLE funcionarios (
	id_funcionario BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(250) NOT NULL,
	cargo VARCHAR(250) NOT NULL,
	idade INTEGER,
	qtd_faltas INTEGER,
	PRIMARY KEY (id_funcionario)
);

-- NOTA: idade e qtd_faltas serão 0 quando não informados
INSERT INTO funcionarios (nome, cargo, idade, qtd_faltas) VALUES
	('Willian Conceição', 'programador jr', 23, 5),
	('Maria Regina', 'CEO', 58, 2),
	('Isaias Fideles', 'Consultor', 68, 3); 

CREATE TABLE pagamentos (
	id_pagamento BIGINT GENERATED BY DEFAULT AS IDENTITY,
	data_vencimento DATE NOT NULL,
	data_aprovacao DATE,
	descricao VARCHAR(500) NOT NULL,
	valor DOUBLE NOT NULL,
	id_solicitante INTEGER NOT NULL,		-- DEVE SER BIGINT
	id_aprovador INTEGER,					-- DEVE SER BIGINT
	PRIMARY KEY (id_pagamento),
	CONSTRAINT id_solicitante FOREIGN KEY (id_solicitante) REFERENCES funcionarios(id_funcionario),
	CONSTRAINT id_aprovador FOREIGN KEY (id_aprovador) REFERENCES funcionarios(id_funcionario)
);
	
INSERT INTO pagamentos (data_vencimento, data_aprovacao, descricao, valor, id_solicitante, id_aprovador) VALUES
	('2020-05-25', '2020-05-19', 'Pagamento licença de software', '25.56', 1, 2);

INSERT INTO pagamentos (data_vencimento, descricao, valor, id_solicitante) VALUES
	('2020-05-30', 'Viajem técnica para configuração do servidor.', '50.00', 1),
	('2020-06-30', 'Implementação de software no cliente.', '100.00', 1);
	
CREATE TABLE detalhes (
	id_detalhe INT AUTO_INCREMENT PRIMARY KEY,
	id_pagamento INT NOT NULL,
	data DATE NOT NULL,
	descricao VARCHAR(250) NOT NULL,
	usuario VARCHAR(250) NOT NULL,
	CONSTRAINT id_pagamento FOREIGN KEY (id_pagamento) REFERENCES pagamentos(id_pagamento)
);

INSERT INTO detalhes (id_pagamento, data, descricao, usuario) VALUES
(1, '2020-05-19', 'Pagamento aprovado.', 'Maria'),
(2, '2020-05-19', 'Pagamento em análise', 'Maria');
